version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      graphql-codegen:
        patterns:
          - "@graphql-codegen/*"
      storybook:
        patterns:
          - "@storybook/*"
          - "storybook*"
    open-pull-requests-limit: 20
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
