# for development purposes
version: "3.8"
services:
  backend:
    image: node:24
    env_file: .env
    volumes:
      - .:/opt/app:delegated
    working_dir: /opt/app
    command: npm run watch -w backend
    network_mode: host
  frontend:
    image: node:24
    volumes:
      - .:/opt/app:delegated
    working_dir: /opt/app
    command: npm run watch -w frontend
    depends_on:
      - backend
    network_mode: host
